name: learn-github-actions

on: [push]

jobs:
  dev:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello from DEV"

  qa:
    runs-on: ubuntu-latest
    needs: dev
    steps:
      - run: echo "Hello from QA"

  uat:
    runs-on: ubuntu-latest
    needs: qa
    steps:
      - run: echo "Hello from UAT"

  prod:
    runs-on: ubuntu-latest
    needs: uat
    steps:
      - run: echo "Hello from PROD"